# Generated by Django 3.1 on 2020-10-12 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_producto_bodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='HISTORiAL_SUBASTA',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('oferta', models.IntegerField()),
                ('fecha_oferta', models.DateTimeField()),
                ('id_subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subasta_transporte')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
