# Generated by Django 3.1 on 2020-10-07 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20201002_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='id_postulacion',
        ),
        migrations.RemoveField(
            model_name='detalle_postulacion',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detalle_postulacion',
            name='fecha_elaboracion',
        ),
        migrations.RemoveField(
            model_name='detalle_postulacion',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='detalle_postulacion',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='detalle_postulacion',
            name='precio',
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proceso_venta'),
        ),
        migrations.AlterField(
            model_name='proceso_venta',
            name='id_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.solicitud_compra'),
        ),
        migrations.CreateModel(
            name='PRODUCTO_BODEGA',
            fields=[
                ('id_prod_bod', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_elaboracion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('precio_kilo', models.IntegerField()),
                ('id_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bodega')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PROCESO_MINORISTA',
            fields=[
                ('id_proceso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_prod_bod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto_bodega')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_postulacion',
            name='id_prod_bod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto_bodega'),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_proceso_mino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proceso_minorista'),
        ),
    ]
