# Generated by Django 3.1 on 2020-10-07 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201006_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso_venta',
            name='id_tipo',
        ),
    ]
