# Generated by Django 3.1 on 2020-10-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historial_subasta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TIPO_PROCESO_VENTA',
        ),
    ]
