# Generated by Django 3.1 on 2020-10-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_proceso_venta_id_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
