# Generated by Django 3.1 on 2020-10-12 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estado_minorista_proceso_minorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='id_proceso_mino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proceso_minorista'),
        ),
    ]
