# Generated by Django 3.1 on 2020-10-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pago_id_proceso_mino'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HISTORIAL_MINORISTA',
            new_name='HISTORIAL_POSTULACION',
        ),
    ]
