# Generated by Django 3.1 on 2020-10-14 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201012_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESTADO_LOTE',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto_bodega',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto_bodega',
            name='fecha_elaboracion',
        ),
        migrations.RemoveField(
            model_name='producto_bodega',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='producto_bodega',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='producto_bodega',
            name='precio_estandar',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='LOTE',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_kilo', models.IntegerField()),
                ('fecha_elaboracion', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('id_esetado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado_lote')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto_bodega',
            name='id_lote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.lote'),
            preserve_default=False,
        ),
    ]
