# Generated by Django 3.1 on 2020-10-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
