# Generated by Django 3.1 on 2020-10-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201013_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fecha_elaboracion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lote',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
    ]
