# Generated by Django 3.1 on 2020-10-10 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESTADO_MINORISTA',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='producto_bodega',
            old_name='precio_kilo',
            new_name='precio_estandar',
        ),
        migrations.RemoveField(
            model_name='proceso_minorista',
            name='fecha',
        ),
        migrations.AddField(
            model_name='postulacion_producto',
            name='fecha_oferta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postulacion_producto',
            name='oferta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceso_minorista',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proceso_minorista',
            name='fecha_termino',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='postulacion_producto',
            name='fecha_publicacion',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='proceso_minorista',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estado_minorista'),
        ),
    ]
