# Generated by Django 3.1 on 2020-10-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201010_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion_producto',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
