# Generated by Django 3.1 on 2020-10-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_postulacion_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion_producto',
            name='id_prod_bod',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.producto_bodega'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DETALLE_POSTULACION',
        ),
    ]
