# Generated by Django 3.1 on 2020-10-20 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20201020_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_subasta',
            name='id_subasta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.subasta_transporte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial_subasta',
            name='id_usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
