# Generated by Django 3.1 on 2020-10-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201020_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HISTORiAL_SUBASTA',
        ),
    ]
