# Generated by Django 3.1 on 2020-10-24 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_historial_subasta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='id_proceso_mino',
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_proceso',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proceso_venta'),
        ),
        migrations.CreateModel(
            name='PRODUCTO_PROCESO',
            fields=[
                ('id_prod_proc', models.AutoField(primary_key=True, serialize=False)),
                ('id_minorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proceso_minorista')),
                ('id_prod_bod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto_bodega')),
            ],
        ),
        migrations.CreateModel(
            name='CARRITO',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('id_prod_proc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto_proceso')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='id_carrito',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carrito'),
        ),
    ]
