# Generated by Django 3.1 on 2020-10-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201024_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial_postulacion',
            old_name='oferta',
            new_name='oferta_x_kilo',
        ),
    ]
