# Generated by Django 3.1 on 2020-10-27 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201026_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='id_dato_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dato_pago'),
        ),
    ]
