# Generated by Django 3.1 on 2020-10-28 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201026_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESTADO_CARRITO',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_estado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.estado_carrito'),
            preserve_default=False,
        ),
    ]
