# Generated by Django 3.1 on 2020-10-28 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201028_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='id_estado',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='id_prod_proc',
        ),
        migrations.RenameModel(
            old_name='ESTADO_CARRITO',
            new_name='ESTADO_PRO_CAR',
        ),
        migrations.CreateModel(
            name='PRODUCTO_CARRITO',
            fields=[
                ('id_prod_car', models.AutoField(primary_key=True, serialize=False)),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrito')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado_pro_car')),
                ('id_prod_proc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto_proceso')),
            ],
        ),
    ]
