# Generated by Django 3.1 on 2020-10-28 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201028_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ESTADO_PRO_CAR',
            new_name='ESTADO_CARRITO',
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_estado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.estado_carrito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_prod_proc',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.producto_proceso'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PRODUCTO_CARRITO',
        ),
    ]
