# Generated by Django 3.1 on 2020-10-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201028_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESTADO_PRODUCTO_CARRITO',
            fields=[
                ('id_estado_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_estado_pro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.estado_producto_carrito'),
            preserve_default=False,
        ),
    ]
