# Generated by Django 3.1 on 2020-10-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20201028_2044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ESTADO_CARRITO',
            new_name='ESTADO_PRODUCTO',
        ),
        migrations.CreateModel(
            name='PRODUCTO_CARRITO',
            fields=[
                ('id_pro_car', models.AutoField(primary_key=True, serialize=False)),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrito')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado_producto')),
                ('id_prod_proc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto_proceso')),
            ],
        ),
    ]
