# Generated by Django 3.1 on 2020-10-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20201029_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='id_estado',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='id_prod_proc',
        ),
    ]
