# Generated by Django 3.1 on 2020-11-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201029_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguro',
            name='id_estado',
        ),
        migrations.DeleteModel(
            name='ESTADO_POLIZA',
        ),
    ]
