# Generated by Django 3.1 on 2020-11-03 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20201103_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_subasta',
            name='id_conclusion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.conclusion'),
            preserve_default=False,
        ),
    ]
