# Generated by Django 3.1 on 2020-11-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_nota_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='id_proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proceso_venta'),
        ),
    ]
