# Generated by Django 3.1 on 2020-11-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20201105_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESTADO_POLIZA',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=30)),
            ],
        ),
    ]
