from django.urls import path
from .views import (
    home,
    registro_minorista,
    codigo_activacion,
    registro_usuario,
    solicitud_compra,
    formulario_solicitud,
    listar_productos,
    agregar_producto,
    anular_solicitud,
    modificar_datos_personales,
    perfil_usuario,
    eliminar_detalleproducto,
    modificar_detalleproducto,
    procesos_venta,
    producto_procesoventa,
    actualizar_pedidorecibido,
    actualizar_pedidoanulado,
    resultado_solicitud,
    aceptar_oferta,
    rechazar_oferta,
    # mis_productos,

)

urlpatterns = [
    path("", home, name="home"),
    path("registro_minorista/", registro_minorista, name="registro_minorista"),
    path("codigo_activacion/", codigo_activacion, name="codigo_activacion"),
    path("registro_usuario/<cod>/", registro_usuario, name="registro_usuario"),
    path("solicitud_compra/", solicitud_compra, name="solicitud_compra"),
    path("formulario_solicitud/", formulario_solicitud, name="formulario_solicitud"),
    path("agregar_producto/<id>/", agregar_producto, name="agregar_producto"),
    path("listar_productos/<id>/", listar_productos, name="listar_productos"),
    path("anular_solicitud/<id>/", anular_solicitud, name="anular_solicitud"),
    path("perfil_usuario/<id>/", perfil_usuario, name="perfil_usuario"),
    path("modificar_datos_personales/<id>/", modificar_datos_personales, name="modificar_datos_personales"),
    path("eliminar_detalleproducto/<id>/", eliminar_detalleproducto, name="eliminar_detalleproducto"),
    path("modificar_detalleproducto/<id>/", modificar_detalleproducto, name="modificar_detalleproducto"),
    path("procesos_venta/", procesos_venta, name="procesos_venta"),
    path("producto_procesoventa/<id_detalle>/<id_proceso>/<id_producto>/", producto_procesoventa, name="producto_procesoventa"),
    path("actualizar_pedidorecibido/<id_solicitud>/", actualizar_pedidorecibido, name="actualizar_pedidorecibido"),
    path("actualizar_pedidoanulado/<id_solicitud>/", actualizar_pedidoanulado, name="actualizar_pedidoanulado"),
    path("resultado_solicitud/<id_solicitud>/", resultado_solicitud, name="resultado_solicitud"),
    path("aceptar_oferta/<id_solicitud>/", aceptar_oferta, name="aceptar_oferta"),
    path("rechazar_oferta/<id_solicitud>/", rechazar_oferta, name="rechazar_oferta"),
    # path("mis_productos/", mis_productos, name="mis_productos"),

]
